### ISSUE TITLE
About the installation

### ISSUE THREAD

**Issue by lyn5466** [colinmeinke/ghost-storage-adapter-s3#1]
I think the original command in the installation `cp -r ./node_modules/ghost-storage-adapter-s3 ./content/storage/s3` should change to `cp -r ./node_modules/ghost-storage-adapter-s3/index.js ./content/storage/s3`

**Comment by colinmeinke** [comment]
Hey, thanks for the issue! The current command copies the whole directory and includes the `node_modules` it depends on).

**Comment by colinmeinke** [comment]
@lyn5466 is it not working for you?

**Comment by lyn5466** [comment]
Hi,
Sorry for the late reply. I used the command, and got the error
`ERROR: We cannot find your adpter in: /app/content/storage or: /app/core/sever/storage`
But if I only copy your `index.js` into `/app/content/storage/s3/`, it works!
The following is the directory structure after typing your command.
By the way, what's difference to only copy the `index.js` into the `/app/content/storage/s3/`? 
Just curious :P
And thank you so much to build the adapter, I have been looking for this for several days!
```
├── storage
│   └── s3
│       └── ghost-storage-adapter-s3
│           ├── index.js
│           ├── LICENSE.md
│           ├── node_modules
│           │   └── bluebird
│           │       ├── changelog.md
│           │       ├── js
│           │       │   ├── browser
│           │       │   │   ├── bluebird.core.js
│           │       │   │   ├── bluebird.core.min.js
│           │       │   │   ├── bluebird.js
│           │       │   │   └── bluebird.min.js
│           │       │   └── release
│           │       │       ├── any.js
│           │       │       ├── assert.js
│           │       │       ├── async.js
│           │       │       ├── bind.js
│           │       │       ├── bluebird.js
│           │       │       ├── call_get.js
│           │       │       ├── cancel.js
│           │       │       ├── catch_filter.js
│           │       │       ├── context.js
│           │       │       ├── debuggability.js
│           │       │       ├── direct_resolve.js
│           │       │       ├── each.js
│           │       │       ├── errors.js
│           │       │       ├── es5.js
│           │       │       ├── filter.js
│           │       │       ├── finally.js
│           │       │       ├── generators.js
│           │       │       ├── join.js
│           │       │       ├── map.js
│           │       │       ├── method.js
│           │       │       ├── nodeback.js
│           │       │       ├── nodeify.js
│           │       │       ├── promise_array.js
│           │       │       ├── promise.js
│           │       │       ├── promisify.js
│           │       │       ├── props.js
│           │       │       ├── queue.js
│           │       │       ├── race.js
│           │       │       ├── reduce.js
│           │       │       ├── schedule.js
│           │       │       ├── settle.js
│           │       │       ├── some.js
│           │       │       ├── synchronous_inspection.js
│           │       │       ├── thenables.js
│           │       │       ├── timers.js
│           │       │       ├── using.js
│           │       │       └── util.js
│           │       ├── LICENSE
│           │       ├── package.json
│           │       └── README.md
│           ├── package.json
│           ├── README.md
│           └── src
│               └── index.js
```

**Comment by colinmeinke** [comment]
@lyn5466 the problem is you have a directory inside `s3` called `ghost-storage-adapter-s3`. That shouldn't be there. All the files should be copied directly to the `s3` directory. 

The `cp -r ./node_modules/ghost-storage-adapter-s3 ./content/storage/s3` command should create a new directory inside `./content/storage` called `s3` and then copy all files from **inside** the `./node_modules/ghost-storage-adapter-s3` directory to the newly created `s3` directory.

**Comment by colinmeinke** [comment]
The difference if you copy `index.js` and not the entire directory is that you won't be copying the dependencies of the library (inc. the AWS SDK).

**Comment by lyn5466** [comment]
Oh, thank you so much! Everything works fine now!

**Comment by colinmeinke** [comment]
No problem 😃
