### ISSUE TITLE
Add a proxy feature for images uploaded before installation of the adapter

### ISSUE THREAD

**Issue by GerardVivancos** [colinmeinke/ghost-storage-adapter-s3#10]
When the adapter is installed it works flawlessly for newly uploaded images but, of course, it does not work for pre-existing ones.

These are usually linked using relative URLs. Because of this, by using the `serve()` method, they can be served from S3 by proxying them from the bucket, provided they are copied there, without needing to edit every link on previously published posts.

We've got a PR ready for this.

**Comment by colinmeinke** [comment]
Sounds good!

**Comment by colinmeinke** [comment]
[Released](https://github.com/colinmeinke/ghost-storage-adapter-s3/releases/tag/v1.3.0). Thanks @GerardVivancos, nice work 😄
