### ISSUE TITLE
Ghost 1.0 compatibility 

### ISSUE THREAD

**Issue by wassimseif** [colinmeinke/ghost-storage-adapter-s3#15]
Does this work on ghost 1.0 ? or any plan to support it ?

**Comment by colinmeinke** [comment]
It currently doesn't. But I will definitely accept a PR when Ghost 1 is released.

**Comment by frippz** [comment]
It's not official yet, but [1.0 is available on Github now](https://github.com/TryGhost/Ghost/releases/tag/1.0.0) and [docs for developing custom storage modules are also available now](https://docs.ghost.org/v1.0.0/docs/using-a-custom-storage-module). 👍🏼

**Comment by frippz** [comment]
@wassimseif In the meantime, have a look at this fork: https://github.com/vstabile/ghost-storage-adapter-s3. Just tested it myself and it seem to work fine.

**Comment by colinmeinke** [comment]
@frippz awesome, that's good enough for me, I'm happy to accept a PR for this now! cc @vstabile

**Comment by vstabile** [comment]
#17

**Comment by colinmeinke** [comment]
Ghost 1 support thanks to @vstabile! - https://github.com/colinmeinke/ghost-storage-adapter-s3/releases/tag/v2.0.0
