### ISSUE TITLE
Ghost 0.11.10 deleting picture 

### ISSUE THREAD

**Issue by wassimseif** [colinmeinke/ghost-storage-adapter-s3#16]
Hello. i have the adapter installed and configured. when i upload an image from the editor and file uploads to the bucket successfully, however, when i delete it, it doesn't get deleted from the bucket. is there a way to delete it automatically ? the delete function is there

**Comment by wassimseif** [comment]
i put a log on the start of  the delete function but it's not getting called

**Comment by colinmeinke** [comment]
Hmm, yeah I have a vague recollection that even though there used to be documentation saying that an adapter should implement a delete method, ghost didn't actually call it on delete. Will happily reopen if you can find the code that proves otherwise.
