### ISSUE TITLE
Region set to 'us-east-1' via Environment Variables does not work

### ISSUE THREAD

**Issue by techwes** [colinmeinke/ghost-storage-adapter-s3#21]
https://github.com/colinmeinke/ghost-storage-adapter-s3/blob/3c98506ab3ff77152cf8b92d423b97d0f3e576ff/src/index.js#L34

The last part of the || should be `` `https://s3${this.region === 'us-east-1' ? '' : `-${this.region}`}.amazonaws.com/${this.bucket}` `` instead. 

I can submit a pull request to fix this or someone already set up to contribute and just make this simple change

**Comment by colinmeinke** [comment]
Yes please, PR away!
