### ISSUE TITLE
Using adapter with a bucket that is private

### ISSUE THREAD

**Issue by geelakey** [colinmeinke/ghost-storage-adapter-s3#32]
I am unable to view the images when connecting to a private bucket. The image gets saved in the bucket just fine, but when viewed in browser I can only see the broken image icon. Copying the image path into the browser I get the following error:

<Code>InvalidArgument
<message>Requests specifying Server Side Encryption with AWS KMS managed keys require AWS Signature Version 4.</message>
</Code>

Do you have any knowledge on how to get this working if the bucket isn't made public?

**Comment by colinmeinke** [comment]
Sorry, I don't. What's the use case? If the blog is publicly accessible, then why isn't the bucket? Closing as I don't think there is a valid reason for this to exist. Will re-open if you can convince me otherwise 😄
