### ISSUE TITLE
PathStyle for s3-like storages

### ISSUE THREAD

**Issue by ulm0** [colinmeinke/ghost-storage-adapter-s3#33]
Hi, I'm trying to setup this adapter in order to use it with Minio as object storage. Thing is Minio uses path style for storing objects. Unlike s3, which uses `bucket.domain.com` Minio one is `domain.com/bucket`

would it possible to use a path style setting in this adapter as well?

**Comment by colinmeinke** [comment]
@Ashald sorted this in e811880aa9458f52fb7e8dae9fa4f088e6f97828, thanks for the issue!
