### ISSUE TITLE
PathPrefix when serving

### ISSUE THREAD

**Issue by dotronglong** [colinmeinke/ghost-storage-adapter-s3#37]
Hi all, I see a problem that if I use `pathPrefix` in configuration, I might not access my current images, although I uploaded them to my proposed folder on S3 already.

For an instance, I create a bucket `long.do` and a folder inside that bucket as `ghost`, then in serving mode it ignores my `pathPrefix`, hence, server returns 404.

Could I make a pull request for it? Btw, my solution is adding `pathPrefix` with ending slash is removed before `req.path` (see more https://github.com/colinmeinke/ghost-storage-adapter-s3/compare/master...dotronglong:features/use-path-prefix-when-serving?expand=1)

**Comment by colinmeinke** [comment]
Thanks! Closed by 133c7a42e8a6775f3cc03be8ac460260fd6f20a6
