### ISSUE TITLE
Does this work with the current Ghost version (2.37.0)?

### ISSUE THREAD

**Issue by acim** [colinmeinke/ghost-storage-adapter-s3#60]
It would be nice if yes :)

**Comment by skj-dev** [comment]
FWIW, I just checked with my recently updated instance. I made a new draft post, dropped an image in it, and verified that it got created in the site's S3 bucket and the corresponding URL pointing to the image worked. 

It's only anecdotal, but it's a 👍 based on a tire kick. 😎

**Comment by acim** [comment]
Great, thank you 😊
