### ISSUE TITLE
this module does not work with ghost being a subapp

### ISSUE THREAD

**Issue by whollacsek** [colinmeinke/ghost-storage-adapter-s3#9]
Because you require the ghost storage base class by doing `../../../core/server/storage/base`, when ghost is installed as an npm module inside an express app this module does not work. [ghost-s3-compat](https://github.com/spanishdict/ghost-s3-compat/blob/master/index.js#L13) is doing `require('ghost/core/server/storage/base')`

**Comment by colinmeinke** [comment]
Hi @whollacsek. I've not used Ghost as a sub app myself, but would love a PR on this. If you can test it still works as standard, that would be great. Thanks!

**Comment by krokofant** [comment]
This other s3 adapter works in my setup where ghost is used mounted in express.
https://github.com/aorcsik/ghost-s3-storage-adapter

Either migrate to that one or perhaps find some inspiration :-) It's a bit confusing with all these s3 adapters available. Hard to know which one to choose.

**Comment by colinmeinke** [comment]
@krokofant not sure of the situation now, but when I created this none of the other s3 adapters supported Ghost 0.10, and the pull requests weren't being merged.

**Comment by jshimko** [comment]
One option here would be to add ghost as a local dependency for the module and then change the `require` to import the base storage class from there.  I've tested this locally and can confirm it works.  The only hassle in installing the entire ghost project to import a single class, but it at least allows you to have whatever folder structure you want outside of the plugin.

So...

```sh
# install ghost inside this module 
npm i -S ghost
```
And then change this...
```js
// https://github.com/colinmeinke/ghost-storage-adapter-s3/blob/master/src/index.js#L2

import BaseStore from '../../../core/server/storage/base'
```
to this...
```js
import BaseStore from 'ghost/core/server/storage/base'
```
Done!  You're in business!

**Comment by colinmeinke** [comment]
This should work with the new release that support Ghost 1, as BaseStore is now it's own module.
